<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Fri, 22 Jun 2012 07:42:04 +0000
 */
$conf['title'] = 'Danis Wiki';
$conf['lang'] = 'en';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['datadir'] = './itdata/pages';
$conf['mediadir'] = './itdata/media';
$conf['metadir'] = './itdata/meta';
